/**
 * Generates docs/th-copy-sheet.md and docs/zh-copy-sheet.md by pairing every
 * translated string with its English source, keyed by its path in the copy
 * module. A reviewer edits the copy module at that path; nothing else moves.
 *
 *   node tools/copy-sheet.mjs
 */
import { writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import en from '../src/content/copy/en.mjs';
import th from '../src/content/copy/th.mjs';
import zh from '../src/content/copy/zh.mjs';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

/** Flattens to { 'home.lede': 'text', 'how.steps[0].h': 'text' }. */
function flatten(obj, prefix = '', out = {}) {
  for (const [k, v] of Object.entries(obj)) {
    if (typeof v === 'function') continue;
    const path = prefix ? (Array.isArray(obj) ? `${prefix}[${k}]` : `${prefix}.${k}`) : k;
    if (v && typeof v === 'object') flatten(v, path, out);
    else if (typeof v === 'string') out[path] = v;
  }
  return out;
}

const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');

async function sheet(lang, target, langName, file, note) {
  const E = flatten(en), T = flatten(target);
  const keys = Object.keys(T).filter((k) => k !== 'code' && k !== 'htmlLang');

  const rows = keys.map((k) => {
    const src = E[k];
    return `| \`${k}\` | ${src ? cell(src) : '_(no English source)_'} | ${cell(T[k])} | |`;
  });

  const missing = Object.keys(E).filter((k) => !(k in T) && !k.startsWith('legal.') === false);
  const body = `# ${langName} copy sheet — for native review

**Status: DRAFT. Not reviewed by a native speaker.**

Every ${langName} string on the site is listed below beside its English source.
This is the only file a reviewer needs to read; corrections go into
\`src/content/copy/${lang}.mjs\` at the \`key\` shown in the first column, then
run \`npm run fonts\` (the Chinese font subset contains only the characters the
site currently uses, so new characters need a rebuild) and \`npm run build\`.

${note}

Generated by \`node tools/copy-sheet.mjs\` — do not edit this file by hand.

**${keys.length} strings.**

| key | English source | ${langName} draft | Reviewer correction |
|---|---|---|---|
${rows.join('\n')}
`;
  await writeFile(join(ROOT, 'docs', file), body);
  console.log(`  docs/${file}  (${keys.length} strings)`);
}

await sheet('th', th, 'Thai', 'th-copy-sheet.md',
  `Points that need a Thai reviewer's judgement in particular:

- **The registered address in Thai** (\`src/content/facts.mjs\` → \`company.addressLines.th\`).
  This was rendered from the English address supplied in the brief and has **not**
  been verified against the company's registration document. Check it character by character.
- **The director's name.** It is shown in Latin script everywhere because the Thai
  spelling was not supplied. If a Thai spelling is wanted, add it to \`facts.mjs\`.
- **The date of registration** is given in Buddhist Era (18 กันยายน 2569). Confirm
  that this is the convention the company profile uses.
- **Legal section 6 (PDPA)** uses statutory terminology. It must be checked by the
  company's Thai legal adviser, not only by a copy reviewer.`);

await sheet('zh', zh, 'Simplified Chinese', 'zh-copy-sheet.md',
  `Scope: Chinese covers the traveller-facing pages only (Home, How it works,
Pricing, 404), per brief §6. Venue Partners is written for a property professional
and Legal requires the company's Thai legal adviser, so those pages stay in
English and Thai; the Chinese pages link through to the English versions and say so.

Note that the registered address is shown in English on Chinese pages, because a
Chinese rendering of a Thai registered address would not match any official record.`);
